[package]
name = "learn-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rusty-hook = "^0.11.2"

[dependencies]

[[bin]]
name = "learn-rust"
path = "main.rs"
